In [1]:
import numpy as np


In [2]:
rnd = np.random.RandomState(0)

In [5]:
w = rnd.normal(size = 3)

In [6]:
w


array([1.76405235, 0.40015721, 0.97873798])

In [7]:
from  sklearn.datasets import load_breast_cancer


In [12]:
cancer.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [14]:
cancer.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [15]:
cancer = load_breast_cancer()

In [16]:
rng = np.random.RandomState(42)

In [17]:
noise =  rng.normal(size = (len(cancer.data), 50))

In [18]:
noise

array([[ 0.49671415, -0.1382643 ,  0.64768854, ...,  1.05712223,
         0.34361829, -1.76304016],
       [ 0.32408397, -0.38508228, -0.676922  , ...,  0.26105527,
         0.00511346, -0.23458713],
       [-1.41537074, -0.42064532, -0.34271452, ..., -1.32045661,
         0.52194157,  0.29698467],
       ...,
       [ 1.11295534,  0.14004307,  0.95501349, ...,  0.05174335,
         1.64878597, -0.13855742],
       [-0.36133539, -0.02436784,  2.17920511, ...,  0.10180644,
        -0.39580383, -0.41925995],
       [ 0.1547812 , -1.00213838, -1.00802206, ...,  0.4845971 ,
         0.14160101, -1.11543425]])

In [22]:
hour = ["%02d:00"  %i for i in range(0,24,3)]
hour

['00:00', '03:00', '06:00', '09:00', '12:00', '15:00', '18:00', '21:00']

In [26]:
day = ["man" , "tue" , "wed" , "th", "fri", "sat","sun"]
day 

['man', 'tue', 'wed', 'th', 'fri', 'sat', 'sun']

In [27]:
features = day + hour

In [28]:
features


['man',
 'tue',
 'wed',
 'th',
 'fri',
 'sat',
 'sun',
 '00:00',
 '03:00',
 '06:00',
 '09:00',
 '12:00',
 '15:00',
 '18:00',
 '21:00']

In [29]:
from sklearn.datasets import load_digits


In [30]:
digits = load_digits()

In [31]:
y = digits.target == 9

In [32]:
y


array([False, False, False, ..., False,  True, False])

In [33]:
y = digits.target
y

array([0, 1, 2, ..., 8, 9, 8])